carla:
  task: carla_rl-gym-v0
  run:
    steps: 1e6
    train_ratio: 64
    log_every: 1e4
  env:
    action_repeat: 2
    time_limit: 300
  encoder:
    cnn_keys: [image]
    mlp_keys: [vector]
    cnn_depth: 32
  rssm:
    deter: 512
    stoch: 32
    classes: 32
  actor:
    layers: 3
    units: 512
  critic:
    layers: 3
    units: 512
